import {
  FiHome,
  FiClock,
  FiPaperclip,
  FiUser,
  FiBookmark,
  FiCode,
  FiZap,
} from "react-icons/fi";

export const actions = [
  {
    id: "home",
    name: "Home",
    shortcut: ["h"],
    keywords: "home",
    perform: () => (window.location.pathname = "/"),
    section: "Navigation",
    icon: FiHome({ size: "1rem" }),
  },
  {
    id: "about",
    name: "About",
    shortcut: ["a"],
    keywords: "about",
    perform: () => (window.location.pathname = "about"),
    section: "Navigation",
    icon: FiUser({ size: "1rem" }),
  },
  {
    id: "links",
    name: "Links",
    shortcut: ["l"],
    keywords: "email link discord twitter github",
    perform: () => (window.location.pathname = "links"),
    section: "Navigation",
    icon: FiPaperclip({ size: "1rem" }),
  },
  {
    id: "now",
    name: "Now",
    shortcut: ["n"],
    keywords: "now",
    perform: () => (window.location.pathname = "now"),
    section: "Navigation",
    icon: FiClock({ size: "1rem" }),
  },
  {
    id: "dashboard",
    name: "Dashboard",
    shortcut: ["d"],
    keywords: "dashboard stars age stats",
    perform: () => (window.location.pathname = "dashboard"),
    section: "Navigation",
    icon: FiZap({ size: "1rem" }),
  },
  {
    id: "blog",
    name: "Blog",
    shortcut: ["b"],
    keywords: "writing words article",
    perform: () => window.open("https://bhaveek.hashnode.dev/", "_blank"),
    section: "External",
    icon: FiBookmark({ size: "1rem" }),
  },
  {
    id: "projects",
    name: "Projects",
    shortcut: ["p"],
    keywords: "projects",
    perform: () => window.open("https://github.com/bhaveek424", "_blank"),
    section: "External",
    icon: FiCode({ size: "1rem" }),
  },
];
